/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * TestRuntime.ls
 */
export class TestRuntimeBase extends Laya.Scene {
    public ButtonA!: Laya.GButton;
    public txtB!: Laya.GTextField;
    public imgC!: Laya.GImage;
}

